# Generated by Django 5.2.7 on 2025-12-18 21:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, help_text='Required for coupon-type discounts', max_length=50, null=True)),
                ('discount_type', models.CharField(choices=[('product_override', 'Product-level price override'), ('cart_subtotal', 'Cart subtotal discount'), ('coupon', 'Coupon'), ('flash_sale', 'Flash sale'), ('abandoned_cart', 'Abandoned cart')], max_length=30)),
                ('value_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed amount')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='If percent, 10 = 10%', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=100, help_text='Lower = applied earlier')),
                ('stackable', models.BooleanField(default=True, help_text='Can it be combined with others?')),
                ('exclusive', models.BooleanField(default=False, help_text='If applied, stop applying lower priority discounts')),
                ('min_cart_subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_abandoned_minutes', models.IntegerField(blank=True, null=True)),
                ('max_profit_share', models.DecimalField(decimal_places=2, default=Decimal('0.75'), help_text='Max % of profit this discount can consume. 0.75 = 75%.', max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_variants', models.ManyToManyField(blank=True, help_text='Empty = applies to all variants (for non-product specific types)', related_name='discounts', to='catalog.productvariant')),
            ],
        ),
    ]
