# Generated by Django 5.2.7 on 2025-12-18 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_transit', 'Customer Shipped Back'), ('received', 'Items Received'), ('refunded', 'Refunded'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('resolution', models.CharField(choices=[('refund', 'Refund'), ('exchange', 'Exchange'), ('store_credit', 'Store Credit')], default='refund', max_length=20)),
                ('reason_general', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
                ('original_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='orders.order')),
                ('replacement_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests_as_replacement', to='orders.order')),
                ('return_issue_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests_as_return', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.PositiveIntegerField()),
                ('reason_code', models.CharField(choices=[('size', 'Wrong size'), ('color', 'Did not like color'), ('damaged', 'Damaged'), ('other', 'Other')], default='other', max_length=20)),
                ('reason_text', models.TextField(blank=True)),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='orders.orderline')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='returns.returnrequest')),
            ],
        ),
    ]
