# Generated by Django 5.2.7 on 2025-10-12 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_shippingaddress_client_mobile2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='client_mobile2',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='أدخل رقم هاتف عراقي صحيح (مثال: 07801234567 أو +9647801234567).', regex='^(?:\\+964|00964|0)?7(7|8|9|5)\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='أدخل رقم هاتف عراقي صحيح (مثال: 07801234567 أو +9647801234567).', regex='^(?:\\+964|00964|0)?7(7|8|9|5)\\d{8}$')]),
        ),
    ]
