# Generated by Django 5.2.7 on 2025-12-18 21:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ('bundle_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/bundles/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/main/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/variants/')),
                ('pricing_mode', models.CharField(choices=[('flat', 'Flat'), ('tiered', 'Tiered')], default='flat', max_length=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('share_inventory_across_tiers', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.bundle')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='catalog.productvariant')),
            ],
            options={
                'unique_together': {('bundle', 'variant')},
            },
        ),
        migrations.AddField(
            model_name='bundle',
            name='variants',
            field=models.ManyToManyField(related_name='bundles', through='catalog.BundleItem', to='catalog.productvariant'),
        ),
        migrations.CreateModel(
            name='VariantOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('color_code', models.CharField(blank=True, max_length=10, null=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.variantoption')),
            ],
        ),
        migrations.AddField(
            model_name='productvariant',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='variants', to='catalog.variantoptionvalue'),
        ),
        migrations.CreateModel(
            name='TieredPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.CharField(choices=[('quantity', 'Quantity'), ('weight', 'Weight')], max_length=10)),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('l', 'Liters')], max_length=10)),
                ('min_value', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('step', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('sku_suffix', models.CharField(blank=True, max_length=40)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['basis', 'unit', 'min_value'],
                'constraints': [models.UniqueConstraint(fields=('variant', 'basis', 'unit', 'min_value', 'max_value'), name='uniq_variant_tier_range')],
            },
        ),
    ]
