# Generated by Django 5.2.7 on 2025-11-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
    ]
