# Generated by Django 5.2.7 on 2025-11-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bundle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/bundles/'),
        ),
    ]
