# Generated by Django 5.2.7 on 2025-12-18 21:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('order_type', models.CharField(choices=[('normal', 'Normal'), ('wholesale', 'Wholesale'), ('replacement', 'Replacement'), ('exchange', 'Exchange'), ('cancellation', 'Cancellation')], default='normal', max_length=20)),
                ('delivery_method', models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pick-up')], default='delivery', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('city_id', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('region_id', models.IntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('location', models.TextField(blank=True)),
                ('client_mobile2', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='أدخل رقم هاتف عراقي صحيح (مثال: 07801234567 أو +9647801234567).', regex='^(?:\\+964|00964|0)?7(7|8|9|5)\\d{8}$')])),
                ('items_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_breakdown', models.JSONField(blank=True, null=True)),
                ('profit_before_discounts', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit_after_discounts', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_free_shipping', models.BooleanField(default=False)),
                ('restock_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to=settings.AUTH_USER_MODEL)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_orders', to='orders.order')),
                ('shipping_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.shippingaddress')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('variant', 'Variant'), ('bundle', 'Bundle')], max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('bundle_name', models.CharField(blank=True, max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='catalog.bundle')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='catalog.productvariant')),
            ],
        ),
    ]
